name: Plugin Submission
description: Submit a new plugin for approval
title: "[PluginSubmission]: "
labels: [plugin-submission]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      # Some cool markdown content
      ## Important Information
      ### Ensure that your:
      - plugin is in a GitHub repository
      - markdown files are renamed (case-sensitive) as PLUGIN.md, README.md
      - plugin manifest file is renamed (case-sensitive) as plugin.json
      - applicable platforms versions are exactly (case-sensitive) as dwcVersion, sbcDSfVersion, rrfVersion.
      Otherwise the checks will not pass.
- type: input
  id: PluginAbstract
  attributes:
    label: Summary
    description: A summary of what your plugin does (Try to keep it below 75 characters)
    placeholder: This plugin...
  validations:
    required: true
- type: input
  id: PluginAuthor
  attributes:
    label: GitHub username
    description: Repo name of the plugin (https://github.com/user/repo)
    placeholder: user
  validations:
    required: true
- type: input
  id: PluginRepo
  attributes:
    label: GitHub repository name
    description: Repo name of the plugin (https://github.com/user/repo)
    placeholder: repo
  validations:
    required: true
- type: input
  id: PluginBranch
  attributes:
    label: GitHub branch name
    description: Name of the main/master branch
    placeholder: main
  validations:
    required: true