name: Plugin Submission
description: Request to remove a plugin
title: "[PluginRemoval]: "
labels: [plugin-removal]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      # Some cool markdown content
      ## Important Information
      - Plugin has to be in a GitHub repository
- type: input
  id: PluginAbstract
  attributes:
    label: Summary
    description: A summary of what your plugin does (Try to keep it below 75 characters)
    placeholder: This plugin...
  validations:
    required: true