name: Plugin Removal
description: Request to remove a plugin
title: "[PluginRemoval]: "
labels: [plugin-removal]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      # Important Information
      - Removal request has to be made from the same account that it was submitted from.
- type: input
  id: PluginID
  attributes:
    label: Plugin ID
    description: Same as repo name
  validations:
    required: true
- type: input
  id: Description
  attributes:
    label: Reason
    description: Reason for removal
    placeholder: I want to remove because
  validations:
    required: true
- type: input
  id: AdditionalInfo
  attributes:
    label: Additional Information
    description: Additional Information
  validations:
    required: false