name: Plugin Removal
description: Request to remove a plugin
title: "[PluginRemoval]: "
labels: [plugin-removal]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      ## Checklist
      ### Ensure that you are:
      - creating the removal request using the same account that the plugin was submitted from
      - stating the reasons for removal clearly (This helps us understand how we can improve the plugin submission/removal process)
      ## Important Information
      - Although the plugin is removed from the repository, it may still exist with any user who may have already downloaded/installed
- type: input
  id: PluginID
  attributes:
    label: Plugin ID
    description: Same as repo name
  validations:
    required: true
- type: input
  id: Description
  attributes:
    label: Reason
    description: Reason for removal
    placeholder: I want to remove because
  validations:
    required: true
- type: input
  id: AdditionalInfo
  attributes:
    label: Additional Information
    description: Additional Information
  validations:
    required: false