name: Plugin Submission
description: Request to remove a plugin
title: "[PluginRemoval]: "
labels: [plugin-removal]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      # Some cool markdown content
      ## Important Information
      - Removal request has to be made from the same account that it was submitted from.
- type: input
  id: PluginID
  attributes:
    label: Summary
    description: A summary of what your plugin does (Try to keep it below 75 characters)
    placeholder: This plugin...
  validations:
    required: true
- type: input
  id: Description
  attributes:
    label: Reason
    description: Reason for removal
    placeholder: I want to remove because
  validations:
    required: true
- type: input
  id: AdditionalInfo
  attributes:
    label: Additional Information
    placeholder: 
  validations:
    required: false