name: Plugin Submission
description: Submit a new plugin for approval
title: "[PluginSubmission]: "
labels: [plugin-submission]
assignees:
- yasasw
body:
- type: markdown
  attributes:
    value: |
      ## Checklist
      ### Ensure that your:
      - plugin is in a GitHub repository
      - repository name/plugin name is not already existing in [Duet3D Plugin Repository](https://github.com/Duet3D/PluginRepository/tree/master/src/plugins)
      - markdown files are renamed (case-sensitive) as PLUGIN.md, README.md
      - Check the content in markdown files against [an online md viewer](https://markdownlivepreview.com/) as sometimes, images might not be displayed correctly
      - If the images are not shown, use the url format `https://raw.githubusercontent.com/<username>/<repo name>/<branch>/<path>/<img name> `
      - plugin manifest file is renamed (case-sensitive) as plugin.json
      - plugin has at least one release
      - plugin release(s) can be downloaded as a zip file.
      Otherwise the checks will not pass.

      ## Important Information
      - Your repository name will be the same as plugin id
      - If a `PLUGIN.md` file exists, it will be used as the homepage of your plugin; otherwise, `README.md` will be used
      - Tags, keywords will be fetched from the plugin manifest(`plugin.json`)
- type: input
  id: PluginAbstract
  attributes:
    label: Summary
    description: A summary of what your plugin does (Try to keep it below 75 characters)
    placeholder: This plugin...
  validations:
    required: true
- type: input
  id: PluginAuthor
  attributes:
    label: GitHub username
    description: Repo owner of the plugin (https://github.com/<user>/repo)
    placeholder: user
  validations:
    required: true
- type: input
  id: PluginRepo
  attributes:
    label: GitHub repository name/Plugin ID
    description: Repo name of the plugin (https://github.com/user/<repo>)
    placeholder: repo
  validations:
    required: true
- type: input
  id: PluginBranch
  attributes:
    label: GitHub branch name
    description: Name of the main/master branch
    placeholder: main
  validations:
    required: true