name: remove-plugin
on:
  issues:
    types: [opened]
jobs:
  issue-label-check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Remove plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_label=$(curl https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/labels | jq -r .[0]."name") 
          if [[ "$issue_label" = plugin-removal ]]; then exit 0; else exit 1; fi
  plugin-removal:
    needs: issue-label-check
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/PluginSubmission.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: Remove plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          commentLog () {
            txt="Log:"
            while IFS= read -r line; do
              echo $line
              txt="$txt \n $line"
            done < checklog.txt

          response="{"\"body"\": "\"$txt"\"}"

          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/labels -d '{"labels":["cannot-be-approved"]}'

          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/comments \
              -d "$response"
          }


          set -e
          cat issue.json
          plugin=$(cat issue.json | jq -r ."plugin_id")
          plugin_file="$plugin".md

          touch checklog.txt

          # 0. Checking if plugin.md exists
          res=$((ls src/plugins/$plugin_file >> /dev/null 2>&1  && echo 1) || echo 0)
          echo Removal-requested plugin exists: $res >> checklog.txt
          echo Removal-requested plugin exists: $res
          if [[ "$res" = 0 ]]; then echo Requested plugin is not available, Exiting >> checklog.txt && commentLog && exit 1; fi


          # 1. Checking if the same user submitted the removal request
          cd src/plugins
          submitted_user=$(sed '2!d' $plugin_file | sed -e "s/plugin_submitted_by://" | tr -d ' ')
          removal_user=${{ github.event.issue.user.login }}
          echo $submitted_user 
          echo $removal_user
          res=$(if [[ "$submitted_user" = "$removal_user" ]]; then echo 1; else echo 0; fi)
          if [[ "$res" = 0 ]]; then echo Request removal using the user $submitted_user for approval. Exiting >> checklog.txt && commentLog && exit 1; fi

          # if all okay, continue


          branchName=removal/$(date +"%y%m%d")$plugin
          commituser=Duet3D

          rm $plugin_file

          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git checkout -b $branchName
          git add $plugin_file
          git commit -m "Deleting plugin plugin_file"
          git push -u origin $branchName

          hub pull-request -m "[${{ github.event.issue.number }}]-$branchName" -l plugin-submission --base $commituser:master --head $commituser:$branchName

          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/labels -d '{"labels":["ready-for-approval"]}'