name: add-tag
on: 
  workflow_dispatch:
    inputs:
      issue_number:
        required: true
  # issues:
  #   types:
  #     - labeled
jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add-tag
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \ 
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.inputs.issue_number }}/labels \
            -d '{"labels":["ready-for-approval"]}'