name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-gh-pages
        run: |
          set -e

          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"

          npm install
          npm run build

          cp CNAME src/.vuepress/dist
          cd src/.vuepress/dist

          git init && git add -A && git commit -m "New Deployment"
          git remote add origin git@github.com:Duet3D/PluginRepository.git
          git push -u origin gh-pages
          # git push -f git@github.com:Duet3D/PluginRepository.git master:gh-pages
