name: deploy
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          set -e

          # git config --global user.name "yasasw"
          # git config --global user.email "yasas.wijetilake@gmail.com"

          npm install
          npm run build

          cp CNAME src/.vuepress/dist
          # cd src/.vuepress

          # git init && git add -A && git commit -m "New Deployment"

          # git push -f https://yasasw:${{secrets.PAT_YASASW}}@github.com:Duet3D/PluginRepository.git master:gh-pages

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_YASASW }}
          publish_dir: ./src/.vuepress/dist
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
