name: gh_page_deploy_latest
on: 
  workflow_dispatch
jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          #!/usr/bin/env sh

          set -e

          npm run build

          cd src/.vuepress/dist

          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          
          git init && git add -A && git commit -m "New Deployment"

          git push -f git@github.com:Duet3D/PluginRepository.git master:gh-pages

          cd -


