name: nodescript_ci_test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          node-version: 18.x
      - name: run test
        run: |
          cd nodescripts
          npm install
          npm test test/