name: remove-plugin-admin
on:
  workflow_dispatch:
    inputs:
      plugin_id:
        required: true
jobs:
  removal-precheck:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/PluginRemoval.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: Remove plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ISSUE: ${{github.event.issue.number}}
          GITHUB_USER: ${{ github.event.issue.user.login }}
        run: |

          cd nodescripts
          npm install
          cd src
          node removalPrecheck2.js