name: submit-new-plugin2
on:
  issues:
    types: [opened]
    
jobs:
  issue-label-check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Remove plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_label=$(curl https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/labels | jq -r .[0]."name") 
          if [[ "$issue_label" = plugin-submission ]]; then exit 0; else exit 1; fi
  precheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_ISSUE: ${{github.event.issue.number}}
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18.x

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser 
        with:
          template-path: .github/ISSUE_TEMPLATE/PluginSubmission.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: precheck-steps
        run: |
          ls -a
          cat issue.json
          cp issue.json nodescripts/src/
          cd nodescripts
          npm install
          cd src
          node preCheck.js
                      
  plugin-submission:
    needs: precheck

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/PluginSubmission.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: Fetch and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ISSUE: ${{github.event.issue.number}}
          GITHUB_USER: ${{ github.event.issue.user.login }}
        run: |

          set -e

          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git pull

          author=$(cat issue.json | jq -r ."PluginAuthor")
          repo=$(cat issue.json | jq -r ."PluginRepo")
          branch=$(cat issue.json | jq -r ."PluginBranch")

          echo $(ls -a)

          cat issue.json
          cp issue.json nodescripts/src/
          cd nodescripts
          npm install
          cd src
          node createPR.js

          cd ../../
          cp nodescripts/src/$repo.md src/plugins

          cd src/plugins 

          branchName=submission/$(date +"%y%m%d")$repo
          commituser=Duet3D
          
          git checkout -b $branchName
          git add $repo.md
          git commit -m "Updating plugin $repo.md"
          git push -u origin $branchName

          hub pull-request -m "[${{ github.event.issue.number }}]-$branchName" -l plugin-submission --base $commituser:master --head $commituser:$branchName

          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/Duet3D/PluginRepository/issues/${{ github.event.issue.number }}/labels -d '{"labels":["ready-for-approval"]}'