name: submit-new-plugin
on:
  issues:
    types: [opened]
jobs:
  plugin-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/PluginSubmission.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: Fetch and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo test 
          echo $(ls -a)

          mv issue.json src/plugins/
          cd src/plugins 


          author=$(cat issue.json | jq ."PluginAuthor" | sed 's/"//g') 
          repo=$(cat issue.json | jq ."PluginRepo" | sed 's/"//g')
          branch=$(cat issue.json | jq ."PluginBranch" | sed 's/"//g')

          title=$(cat issue.json | jq ."PluginTitle")
          abstract=$(cat issue.json | jq ."PluginAbstract")

          branchName=submission/$(date +"%y%m%d")$repo
          commituser=Duet3D


          latest_version=$(curl https://api.github.com/repos/$author/$repo/releases | jq .[0]."tag_name")
          release_date=$(curl https://api.github.com/repos/$author/$repo/releases | jq .[0]."published_at")
          license=$(curl https://raw.githubusercontent.com/$author/$repo/$branch/plugin.json | jq ."license")
          download_count=$(curl https://api.github.com/repos/$author/$repo/releases | jq .[]."assets"[0]."download_count" | paste -sd+ | bc)


          wget https://raw.githubusercontent.com/$author/$repo/$branch/README.md -O $repo.md

          touch frontmatter.txt
          echo --- >> frontmatter.txt
          echo title: $title >> frontmatter.txt
          echo abstract: $abstract >> frontmatter.txt
          echo author: $author >> frontmatter.txt
          echo repo: $repo >> frontmatter.txt
          echo branch: $branch >> frontmatter.txt
          echo latest_version: $latest_version >> frontmatter.txt
          echo release_date: $release_date >> frontmatter.txt
          echo license: $license >> frontmatter.txt
          echo download_count: $download_count >> frontmatter.txt
          echo tags: >> frontmatter.txt
          curl https://raw.githubusercontent.com/$author/$repo/$branch/plugin.json | jq ."tags"[] | awk '{print "\t - ",$0}' >> frontmatter.txt 
          echo --- >> frontmatter.txt

          i=1
          j='i'
          while IFS= read -r line; do
            sed -i "$i$j$line" $repo.md
            i=`expr $i + 1`
          done < frontmatter.txt

          rm frontmatter.txt
          rm issue.json
          
          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git checkout -b $branchName
          git add $repo.md
          git commit -m "Updating plugin $repo.md"
          git push -u origin $branchName

          hub pull-request -m "[${{ github.event.issue.number }}]-$branchName" -l plugin-submission --base $commituser:master --head $commituser:$branchName