name: test
on:
  issues:
    types:
      - labeled
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
            echo ${{ github.event.issue.number }}
            echo ${{ github.event.label.name }}