name: test
on: 
  workflow_dispatch:
    inputs:
          issue_number:
            description: 'Issue number'
            required: true
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: listPullRequests
        run: |
          url=$(curl \
          -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/Duet3D/PluginRepository/pulls \
          | jq '.[] | select(.title | startswith("[${{ github.event.inputs.issue_number }}]"))' | jq ."url" | sed 's/"//g')/merge

          echo $url
      # - name: listPullRequests
      #   uses: buildsville/list-pull-requests@v1
      #   id: list
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     labels: '["plugin-submission"]'
      #     skip_hour: '0'
      # - name: output
      #   run: echo '${{ steps.list.outputs.pulls }}'